services:
  - type: web
    name: jobshield-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb://dhanya14subramaniam_db_user:Siet2024@ac-7gr0ogb-shard-00-00.luk8rv2.mongodb.net:27017,ac-7gr0ogb-shard-00-01.luk8rv2.mongodb.net:27017,ac-7gr0ogb-shard-00-02.luk8rv2.mongodb.net:27017/jobshield?retryWrites=true&w=majority&ssl=true&authSource=admin
      - key: JWT_SECRET
        value: jobshield_jwt_secret_key_2024_secure
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: BREVO_API_KEY
        sync: false
      - key: CLIENT_URL
        value: "*"
